### ISSUE TITLE
pytest 6.1 compatibility

### ISSUE THREAD

**Issue by last-partizan** [theY4Kman/pytest-common-subject#1]
Please, update requirements to support pytest 6.1

**Comment by theY4Kman** [comment]
Sorry for missing this issue! I just published [version 1.0.5](https://pypi.org/project/pytest-common-subject/1.0.5/) to PyPI, which formally supports pytest 6.1 — and also relaxes the version pinning to allow all 6.x versions.

**Comment by last-partizan** [comment]
Nice, thank you!
